### ISSUE TITLE
LDQ shoutout

### ISSUE THREAD

**Issue by stopfstedt** [ilios/iliosproject.org#108]
Loki should be acknowledged in some form for his past contributions to Ilios. Somewhere on the [team page](https://www.iliosproject.org/team/) would be the obvious choice, perhaps in an "emeritus" section or the likes with other former contributors.

**Comment by Trott** [comment]
A listing of Emeriti/Alumni/some-other-fancy-Latin-word might be appropriate. Perhaps another consideration might be an AUTHORS.txt file for the main repository.

**Comment by stopfstedt** [comment]
Rolf needs the same treatment.
