### ISSUE TITLE
Convert all images to SVG

### ISSUE THREAD

**Issue by saschaben** [ilios/iliosproject.org#17]
to improve rendering

**Comment by jrjohnson** [comment]
Agreed.  The hard one is the sunburst Ilios logo I think.  I was going to look around on fiver and see if there was an artist who would do this for us.

**Comment by Trott** [comment]
Seems like the logos are SVG and I'm not sure it makes sense to convert anything else to SVG. Close?

**Comment by michaelchadwick** [comment]
I agree with @Trott that converting the few images on the site to SVG doesn't seem to improve much. The Google Lighthouse scores are all in the green. Does this issue need to remain open?

**Comment by jrjohnson** [comment]
Must have gotten the logo converted at some point. Let's call it a win and close.
