### ISSUE TITLE
Main Nav Bar Not Indicating Current Location

### ISSUE THREAD

**Issue by dartajax** [ilios/iliosproject.org#199]
See below ...

![image](https://user-images.githubusercontent.com/7493331/206302204-f0f3d2a3-aed8-40e9-bbeb-207ad3b57b1f.png)

![image](https://user-images.githubusercontent.com/7493331/206302497-b10e76cc-3960-4f58-8abc-14bce67eaec0.png)

**Comment by stopfstedt** [comment]
https://vilcins.medium.com/applying-the-active-class-for-the-current-page-in-jekyll-426d10ff97
