### ISSUE TITLE
Missing remote slackin.js script being called

### ISSUE THREAD

**Issue by michaelchadwick** [ilios/iliosproject.org#230]
![Screenshot 2024-07-11 at 9 36 19 AM](https://github.com/ilios/iliosproject.org/assets/2374391/813796d5-e2f0-4b3f-88b3-444c03c40cf8)

**Comment by michaelchadwick** [comment]
@stopfstedt I'm assuming I can just remove this script?

**Comment by jrjohnson** [comment]
Yes. You can take this entire chunk out of the site. We used to use this to get people into slack, but haven't been maintaining it and I think it died when heroic started charging. Might be worth looking for a replacement way to get someone signed up for Ilios slack, but I'd be ok removing it and creating a new ticket for the difference.

**Comment by michaelchadwick** [comment]
@jrjohnson https://web.archive.org/web/20220121042521/https://ilios-slack.herokuapp.com/slackin.js (looks like a wombat infestation (see first few lines of file))

**Comment by michaelchadwick** [comment]
I grabbed the archived version, loaded it locally, and finagled some CSS. Is this what it's _supposed_ to look like?
![Screenshot 2024-07-12 at 9 01 09 AM](https://github.com/user-attachments/assets/78a1467f-0bfc-4379-aa48-375c9ed59d70)

**Comment by jrjohnson** [comment]
I don't remember, I think it was a little icon of slack and it said how many people were in the team and if you clicked it you'd be asked for your email and auto invited into the workspace. IIRC we deployed it to heroku with a button out of a GitHub repo. Something I probably wouldn't do today.
