### ISSUE TITLE
Update technology section

### ISSUE THREAD

**Issue by jrjohnson** [ilios/iliosproject.org#92]
We need to update https://github.com/ilios/iliosproject.org/blob/master/technology.md to reflect that we no longer support PHP versions  < 7.0 as well as take a look at our recommendations for OS.

**Comment by stopfstedt** [comment]
still needs to happen. ping @thecoolestguy

**Comment by michaelchadwick** [comment]
Looks like the PHP version req got updated by @saschaben a couple years ago. Not sure about the OS or MySQL requirements.

**Comment by jrjohnson** [comment]
Suggest un-hard-coding the PHP version and pointing at https://github.com/ilios/ilios/blob/master/docs/ilios_php_version_policy.md instead (we're currently on 8.3)
